#ifndef DE_COMPONENTS_COLLISION_LAYER_COMPONENT_HPP
#define DE_COMPONENTS_COLLISION_LAYER_COMPONENT_HPP

namespace de
{
struct CollisionLayerComponent
{
};

} // namespace de

#endif // DE_COMPONENTS_COLLISION_LAYER_COMPONENT_HPP
